local M = {
  diagnostics = {
    -- Error = " ",
    ERROR = " ",
    -- Warn = " ",
    WARN = "󰳥 ",
    HINT = "󰛩 ",
    INFO = " ",
  },
  file = {
    default = "",
    symlink = "",
    modified = '',
    readonly = '',
    unnamed = '',
    newfile = ''
  },
  folder = {
    symlink = "",
    default = "󰪥",
    -- open = "󰪟",
    open = "󰪠",
    empty = "󰝦",
    empty_open = "󰝦",
    -- pending = "󰪡",
    arrow_closed = '+',
    arrow_open = '-',
  },
  git = {
    added = " ",
    modified = " ",
    removed = " ",
    head = "",

    -- nvim-tree
    unstaged = '',
    -- unstaged = '+',
    staged = "✓",
    unmerged = "",
    renamed = "➜",
    untracked = '',
    deleted = '󰍴'
    -- untracked = "★"
  },
  kinds = {
    Array = "",
    Boolean = "",
    Class = "",
    Color = "󰏘",
    Constant = "󰏿",
    Constructor = "",
    Copilot = "",
    Enum = "",
    EnumMember = "",
    Event = "",
    Field = "󰜢",
    File = "󰈙",
    Folder = "󰉋",
    Function = "󰊕",
    Interface = "",
    Key = "󰌋",
    Keyword = "󰌋",
    Method = "",
    Module = "",
    Namespace = "",
    Null = "ﳠ",
    Number = "",
    Object = "",
    Operator = "",
    Package = "",
    Property = "󰜢",
    Reference = "",
    Snippet = "",
    String = "",
    Struct = "",
    Text = "󰉿",
    TypeParameter = "",
    Unit = "󰑭",
    Value = "󰎠",
    Variable = "󰀫",
  },
  misc = {
    Bell = "",
    Gear = "󰢻",
    Vim = "",
    Emacs = "",
    Apple = "",
    Arch = "",
    Devil = "󰱯",
    Robot = "󱚤",
    Term = "",
    SeparatorLeft = "",
    SeparatorRight = "",
    VertSeparator = "",
    Check = "",
    Record = '',
    Search = '',
    VerticalBar = "▏",
    VerticalBar1 = '│',
    Arrow = "➜",
  }
}

return M
