local M = {
  diagnostics = {
    Error = " ",
    Warn = " ",
    Hint = "󰌵 ",
    Info = " ",
  },
  file = {
    modified = '',
    readonly = '',
    unnamed = '',
    newfile = ''
  },
  git = {
    added = " ",
    modified = " ",
    removed = " ",
  },
  kinds = {
    Array = " ",
    Boolean = " ",
    Class = " ",
    Color = " ",
    Constant = " ",
    Constructor = " ",
    Copilot = " ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = " ",
    Folder = " ",
    Function = " ",
    Interface = " ",
    Key = " ",
    Keyword = " ",
    Method = " ",
    Module = " ",
    Namespace = " ",
    Null = "ﳠ ",
    Number = " ",
    Object = " ",
    Operator = " ",
    Package = " ",
    Property = " ",
    Reference = " ",
    Snippet = " ",
    String = " ",
    Struct = " ",
    Text = " ",
    TypeParameter = " ",
    Unit = " ",
    Value = " ",
    Variable = " ",
  },
  misc = {
    Bell = "",
    Gear = " ",
    Vim = "",
    Emacs = "",
    Apple = "",
    Arch = "",
    SeparatorLeft = "",
    SeparatorRight = "",
  }
}

return M
