local M = {
  diagnostics = {
    -- Error = " ",
    Error = " ",
    -- Warn = " ",
    Warn = "󰳥 ",
    Hint = "󰛩 ",
    Info = " ",
  },
  file = {
    default = "",
    symlink = "",
    modified = '',
    readonly = '',
    unnamed = '',
    newfile = ''
  },
  folder = {
    symlink = "",
    default = "󰪥",
    open = "󰪟",
    empty = "󰝦",
    empty_open = "󰝦",
    -- pending = "󰪡",
    arrow_closed = '+',
    arrow_open = '-',
  },
  git = {
    added = " ",
    modified = " ",
    removed = " ",

    -- nvim-tree
    unstaged = '',
    -- unstaged = '+',
    staged = "✓",
    unmerged = "",
    renamed = "➜",
    untracked = '',
    deleted = '󰍴'
    -- untracked = "★"
  },
  kinds = {
    Array = " ",
    Boolean = " ",
    Class = " ",
    Color = " ",
    Constant = " ",
    Constructor = " ",
    Copilot = " ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = " ",
    Folder = " ",
    Function = " ",
    Interface = " ",
    Key = " ",
    Keyword = " ",
    Method = " ",
    Module = " ",
    Namespace = " ",
    Null = "ﳠ ",
    Number = " ",
    Object = " ",
    Operator = " ",
    Package = " ",
    Property = " ",
    Reference = " ",
    -- Snippet = " ",
    Snippet = " ",
    String = " ",
    Struct = " ",
    Text = " ",
    TypeParameter = " ",
    Unit = " ",
    Value = " ",
    Variable = " ",
  },
  misc = {
    Bell = "",
    Gear = "󰢻",
    Vim = "",
    Emacs = "",
    Apple = "",
    Arch = "",
    Devil = "󰱯",
    Robot = "󱚤",
    Term = "",
    SeparatorLeft = "",
    SeparatorRight = "",
    VertSeparator = "",
    Check = "",
  }
}

return M
