palette = "catppuccin_mocha"

[aws]
disabled = true

[battery]
disabled = true

[character]
success_symbol = "[⤚](bold green)"
error_symbol = "[⤚](bold red)"
vicmd_symbol = "[⤙](bold green)"

[cmake]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[directory]
truncation_length = 8
truncate_to_repo = false
style = "bold lavender"

# [docker_context]

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[env_var]
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[git_branch]
symbol = " "

# [git_commit]

# [git_state]

# [git_status]

[golang]
disabled = true

# [hostname]

# [java]

# [jobs]

[julia]
disabled = true

# [kubernetes]

# [line_break]

[lua]
disabled = true

# [memory_usage]

# [hg_branch]

[nim]
disabled = true

[nix_shell]
disabled = true

# [nodejs]

# [package]

[ocaml]
disabled = true

[openstack]
disabled = true

[perl]
disabled = true

[php]
disabled = true

# [python]

[ruby]
disabled = true

# [rust]

# [shlvl]

[singularity]
disabled = true

[swift]
disabled = true

# [status]

# [terraform]

# [time]

# [username]

[zig]
disabled = true

[purescript]
disabled = true

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
