[aws]
disabled = true

[battery]
disabled = true

[character]
success_symbol = "[⤚](bold green)"
error_symbol = "[⤚](bold red)"
vicmd_symbol = "[⤙](bold green)"

[cmake]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[dart]
disabled = true

[directory]
truncation_length = 8
truncate_to_repo = false
style = "bold lavender"

# [docker_context]

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[env_var]
disabled = true

[erlang]
disabled = true

[gcloud]
disabled = true

[git_branch]
symbol = " "

# [git_commit]

# [git_state]

# [git_status]

[golang]
disabled = true

# [hostname]

# [java]

# [jobs]

[julia]
disabled = true

# [kubernetes]

# [line_break]

[lua]
disabled = true

# [memory_usage]

# [hg_branch]

[nim]
disabled = true

[nix_shell]
disabled = true

# [nodejs]

# [package]

[ocaml]
disabled = true

[openstack]
disabled = true

[perl]
disabled = true

[php]
disabled = true

# [python]

[ruby]
disabled = true

# [rust]

# [shlvl]

[singularity]
disabled = true

[swift]
disabled = true

# [status]

# [terraform]

# [time]

# [username]

[zig]
disabled = true

[purescript]
disabled = true
