theme = "kanagawa-dragon-improved"

[editor]
default-yank-register = '+'
true-color = true
undercurl = true
color-modes = true
line-number = "relative"
insert-final-newline = false
popup-border = 'all'
shell = ["zsh", "-c"]
end-of-line-diagnostics = "error"

[editor.statusline]
right = ["diagnostics", "version-control", "selections", "position-percentage", "file-encoding"]

[editor.cursor-shape]
insert = 'bar'
select = "underline"

[editor.indent-guides]
render = true
character = "▏"

[editor.whitespace.render]
newline = "none"
tab = "all"

[editor.whitespace.characters]
newline = ""

[keys.insert]
C-s = "signature_help"

[keys.normal]
"$" = "goto_line_end"
"0" = "goto_line_start"
"_" = "goto_first_nonwhitespace"
S-d = "kill_to_line_end"
esc = ["collapse_selection", "keep_primary_selection"]
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
