# Customize to your needs...

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Not share command history between tmux panes
setopt noincappendhistory
setopt nosharehistory

eval "$(zoxide init zsh)"
eval "$(starship init zsh)"

source ~/.config/zsh/plugins/fzf-tab/fzf-tab.plugin.zsh
source ~/.config/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.config/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.config/zsh/plugins/zsh-vi-mode/zsh-vi-mode.zsh

# fzf-tab config
autoload -Uz compinit && compinit
# set list-colors to enable filename colorizing
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
# preview directory's content with exa when completing cd
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -l --tree --icons --color=always $realpath'
# Bindings
zstyle ':fzf-tab:*' fzf-bindings 'tab:toggle+down,shift-tab:toggle+up'

export PNPM_HOME="$HOME/.pnpm"
export GEM_HOME=$HOME/.gem
export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-24.jdk/Contents/Home
export ANDROID_HOME=$HOME/Library/Android/sdk
export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk
PATH="/usr/local/opt/ruby/bin:$GEM_HOME/bin:$PATH:$HOME/.local/flutter/bin:$HOME/.yarn/bin:$PNPM_HOME:$HOME/.local/bin:$HOME/go/bin"
# export PATH="/usr/local/opt/ruby/bin:$GEM_HOME/bin:$PATH"
PATH=$PATH:$ANDROID_SDK_ROOT/emulator
PATH=$PATH:$ANDROID_SDK_ROOT/tools
PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools

# ctop and colima
export DOCKER_HOST="unix://$HOME/.config/colima/docker.sock"

## [Completion]
## Completion scripts setup. Remove the following line to uninstall
[[ -f /Users/omerta/.config/.dart-cli-completion/zsh-config.zsh ]] && . /Users/omerta/.config/.dart-cli-completion/zsh-config.zsh || true
## [/Completion]


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$('/Users/omerta/miniconda/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
# if [ $? -eq 0 ]; then
#     eval "$__conda_setup"
# else
if [ -f "/Users/omerta/miniconda/etc/profile.d/conda.sh" ]; then
    . "/Users/omerta/miniconda/etc/profile.d/conda.sh"
else
    export PATH="/Users/omerta/miniconda/bin:$PATH"
fi
# fi
# unset __conda_setup
# <<< conda initialize <<<

eval "$(mise activate zsh)"
